[package]
name = "bdk-ffi"
version = "0.27.1"
authors = ["Steve Myers <steve@notmandatory.org>", "Sudarsan Balaji <sudarsan.balaji@artfuldev.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
#crate-type = ["staticlib", "cdylib"]
#crate-type = ["cdylib"]
name = "bdkffi"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = ["uniffi/cli"]

[dependencies]
bdk = { version = "0.27.1", features = ["all-keys", "use-esplora-ureq", "sqlite-bundled", "rpc", "compact_filters"] }
uniffi = { version = "0.23.0" }

[build-dependencies]
uniffi = { version = "0.23.0", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.23.0", features = ["bindgen-tests"] }
assert_matches = "1.5.0"
